name: myUltraWarps
main: REALDrummer.myUltraWarps
version: 7
softdepend: [Vault]
description: >
             This super simple plugin has so many features your head may just implode.
commands:
   back:
      aliases: [return, last]
      description: This command warps you to the last location you warped.
      usage: |
           /<command> (amount)
   change:
      aliases: [modify]
      description: This command modifies properties of an existing warp.
      usage: |
           /<command> ("warp") (owner's) [warp] (name:[new name]) (type:[open/secret/advertised/private]) (warp:[message]) (nowarp:[message]) (giveto:[player])
   changewarp:
      aliases: [modifywarp]
      description: This command modifies properties of an existing warp.
      usage: |
           /<command> (owner's) [warp] (name:[new name]) (type:[open/secret/advertised/private]) (warp:[message]) (nowarp:[message]) (giveto:[player])
   create:
      aliases: [make, set, new, add]
      description: This command creates a named warp at your current location.
      usage: |
           /<command> ("warp") [warp] (type:[open/secret/advertised/private]) (warp:[message]) (nowarp:[message]) (giveto:[player])
   createwarp:
      aliases: [makewarp, setwarp, newwarp, addwarp]
      description: This command creates a named warp at your current location.
      usage: |
           /<command> [warp] (type:[open/secret/advertised/private]) (warp:[message]) (nowarp:[message]) (giveto:[player])
   default:
      aliases: []
      description: The command change the default warp or no warp message for a player, group, or the entire server.
      usage: |
           /<command> ("warp"/"nowarp"/"no warp") ("message") ("for" [player]/"group:"[group]/"server"/"global"] [message]
   delete:
      aliases: [remove]
      description: The command deletes the specified warp.
      usage: |
           /<command> ("warp") (owner's) [warp]
   deletewarp:
      aliases: [removewarp]
      description: The command deletes the specified warp.
      usage: |
           /<command> (owner's) [warp]
   forward:
      aliases: [fwd]
      description: This command moves you forward through your warping history.
      usage: |
           /<command> (amount)
   from:
      aliases: [pull, yank, bring, get]
      description: This command teleports the specified player to you.
      usage: |
           /<command> [player]
   full:
      aliases: [entire, complete]
      description: This command lists all the warps or switches.
      usage: |
           /<command> warp(s) list OR /<command> switch(es) list
   fullswitchlist:
      aliases: [entireswitchlist, completeswitchlist, fullswitcheslist, entireswitcheslist, completeswitcheslist]
      description: This command lists all the switches.
      usage: |
           /<command>
   fullwarplist:
      aliases: [entirewarplist, completewarplist, fullwarpslist, entirewarpslist, completewarpslist]
      description: This command lists all the warps.
      usage: |
           /<command>
   home:
      aliases: []
      description: This command warps you to a warp called "home".
      usage: |
           /<command> (owner's)
   jump:
      aliases: [j]
      description: This command teleports you to the spot that you're pointing at.
      usage: |
           /<command>
   link:
      aliases: []
      description: This command links the targeted button with the specified warp.
      usage: |
           /<command> (owner's) [warp name]
   max:
      aliases: [maximum]
      description: This command sets the maximum number of warps that players on the server, players in a group, or a specific player can make.
      usage: |
           /<command> warps ("for" [player]/"group:"[group]/"server"/"global") [#/"infinite"/"infinity"]
   maxwarps:
      aliases: [maximumwarps]
      description: This command sets the maximum number of warps that players on the server, players in a group, or a specific player can make.
      usage: |
           /<command> ("for" [player]/"group:"[group]/"server"/"global") [#/"infinite"/"infinity"]
   move:
      aliases: [translate]
      description: This command moves a warp to your current location.
      usage: |
           /<command> ("warp") (owner's) [warp]
   movewarp:
      aliases: [translatewarp]
      description: This command moves a warp to your current location.
      usage: |
           /<command> (owner's) [warp]
   mUW:
      aliases: []
      description: This command updates the save files with all the new info from the server or loads all the data from the save files to the server.
      usage: |
           /mUW [load/save] (the) [warps/switches/config]
   myUltraWarps:
      aliases: []
      description: This command updates the save files with all the new info from the server or loads all the data from the save files to the server.
      usage: |
           /myUltraWarps [load/save] (the) [warps/switches/config]
   send:
      aliases: []
      description: This command teleports the designated player to the designated warp, player, or place.
      usage: |
           /<command> [player] ("to") ["there"/"warp" [warp]/"player" [player]]
   set:
      aliases: []
      description: This command creates an unlisted, restricted warp called "home" or sets the location of the spawn point.
      usage: |
           /<command> home (owner's) OR /<command> spawn
   sethome:
      aliases: []
      description: This command creates an unlisted, restricted warp called "home".
      usage: |
           /<command> (owner's)
   setspawn:
      aliases: []
      description: This command sets the spawn point.
      usage: |
           /<command>
   spawn:
      aliases: []
      description: This command teleports you to the spawn point.
      usage: |
           /<command>
   switch:
      aliases: []
      description: This command displays info on the switch that you're pointing at or lists info on the switches that are linked to a designated warp.
      usage: |
           /<command> info OR /<command> list
   switches:
      aliases: []
      description: This command lists info on the switches that are linked to a designated warp.
      usage: |
           /<command> list
   switchlist:
      aliases: [switcheslist]
      description: This command lists info on the switches that are linked to a designated warp.
      usage: |
           /<command>
   switchinfo:
      aliases: []
      description: This command displays info on the switch that you're pointing at or lists info on the switches that are linked to a designated warp.
      usage: |
           /<command>
   to:
      aliases: [find]
      description: This command teleports you to the specified player.
      usage: |
           /<command> [player]
   top:
      aliases: [t]
      description: This command teleports you to the highest solid block directly above you.
      usage: |
           /<command>
   unlink:
      aliases: []
      description: This command unlinks the warp from a switch or unlinks all switches from a warp.
      usage: |
           /<command> (owner's) (warp name)
   warp:
      aliases: []
      description: This command teleports you to a saved warp location or to a set of coordinates.
      usage: |
           /<command> (owner's) [warp] OR /<command> (world) [x] [y] [z] (world) OR /<command> list
   warpinfo:
      aliases: []
      description: This command displays all the info about the warp.
      usage: |
           /<command> (owner's) [name]
   warplist:
      aliases: [warpslist]
      description: This command lists all your warps and all listed warps.
      usage: |
           /<command>
   warps:
      aliases: []
      description: This command lists all your warps and all listed warps or lists all warps in an indicated area.
      usage: |
           /<command> ("list") OR /<command> around
   warpsaround:
      aliases: []
      description: This command lists all warps in an indicated area.
      usage: |
           /<command>
   warptocoord:
      aliases: []
      description: This command teleports you to a set of coordinates.
      usage: |
           /<command> (world) [x] [y] [z] (world)